### ISSUE TITLE
Problems when saving a file in Atom

### ISSUE THREAD

**Issue by cipherstream** [mikegedelman/atom-force#1]
There is a message that pops up indicating that there was an error saving the class file in that it cannot read the _instance url_ value of "undefined".  However, when I look at the _.atomforce_ file that is created when you add a "nature" to the project.  I can see that there is indeed a value for the _instance url_ property.  Also, I can deploy the file to the sandbox org with no problems (except those that normally halt a deployment).  Shouldn't the save feature simple write changes back to the org?

**Comment by mikegedelman** [comment]
I think this happens when you save a file directly after you initialize a project. Can you restart Atom and see if it lets you save then?

**Comment by cipherstream** [comment]
You are correct sir!  Once I restarted Atom (and activated the project) I was able to save the files with no trouble.

**Comment by mikegedelman** [comment]
Published version `v0.3.3`, which fixes this and another small bug I found. Thanks!
