### ISSUE TITLE
New problems when saving file...

### ISSUE THREAD

**Issue by cipherstream** [mikegedelman/atom-force#2]
SfConnection emitted saveError with args ["utilityCls.cls",{"errorCode":"UNKNOWN_EXCEPTION","body":[{"message":"An unexpected error occurred. Please include this ErrorId if you contact support: 142161013-140784 (624007939)","errorCode":"UNKNOWN_EXCEPTION"}],"statusCode":500}]

pulled this error message out of the Developer Tools "console" on Atom.

Thoughts?  I tried killing Atom and starting it again, and activating the project.  No luck. :(

**Comment by cipherstream** [comment]
Not sure if it is related, but there exists a line in the console output of Atom that indicates "Error: duplicate value found: Name duplicates value on record with id: 1dc560000006LAE"

Perhaps this is triggered by the "save" process?

**Comment by mikegedelman** [comment]
If you go to dev console and query `SELECT Id, Name FROM MetadataContainer` with "Use Tooling API" checked, you should have a record called `atom-force-deploy`. If you delete it, it should solve your problem in the short term.

The issue is, I still haven't figured out the best way to handle MetadataContainer. You have to create one to deploy Apex stuff, but once the deploy is successful you have to delete it and create a new one (I think). Currently atom-force tries to delete it every time after a deploy, but sometimes it misses for one reason or another. I might take a stab at updating this over the weekend.

**Comment by cipherstream** [comment]
Yep...that fixed the issue for me.  Maybe you could also delete and recreate every time the user calls an "activate" from the menu.  That would at least remove the necessity of going to the developer console to kill a container.  Also, maybe consider executing the activate each time that the atom session is started for "projects" that are salesforce development projects.  I guess you would need to only activate if you could identify a sessionId to apply to the project.

**Comment by cipherstream** [comment]
Related to this issue, I think, is that whenever the Tooling API returns an error upon save (e.g. "expecting a ';' and instead found a ',' " ), I no longer receive messages from the atom-force indicating it is attempting to save changes to the "org".  Instead, I have to re-add the nature back to the project, then delete the metadatacontainer that was created.  At which point, I can save to the "org" again.  I think this is related to the issue as you described earlier with the metadatacontainer "cleanup".

**Comment by mikegedelman** [comment]
I can't reproduce that last issue. You're saying if you save and the file doesn't compile, then all subsequent saves don't try to save to the server? Does restarting Atom solve it, or do you always have to delete and re-add nature?

What's your console output look like after you save and the compile fails?

**Comment by cipherstream** [comment]
On my Mac, i get a blue message box popup that usually says atom-force is
attempting to save a file.  In the event the compilation fails, there will
be a red box with the message that returns from the server saying something
like "Expected a ; and found a <"  or some similar compile time anomaly.
If I then fix the file to remedy the anomaly and attempt to save, I get no
message box popup.  I don't even get the message box when I attempt to
activate the org/nature.  Nor, do I get that message if I attempt to add
the nature.  I don't even get the popup to "allow access...".  I have to go
kill the metadatacontainer and then activate before I can save.

I will attempt this on my Windows 10 box to see if I get a similar scenario.

On Fri, Jun 24, 2016 at 10:37 AM, Mike Gedelman notifications@github.com
wrote:

> I can't reproduce that last issue. You're saying if you save and the file
> doesn't compile, then all subsequent saves don't try to save to the server?
> Does restarting Atom solve it, or do you always have to delete and re-add
> nature?
> 
> What's your console output look like after you save and the compile fails?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/mikegedelman/atom-force/issues/2#issuecomment-228379211,
> or mute the thread
> https://github.com/notifications/unsubscribe/AA7e2xRKMfhvktUjWBEfCo3RxmyzPyi2ks5qO_m5gaJpZM4I8VXi
> .

## 

To know is to have knowledge.....to understand is to be enlightened.

**Comment by cipherstream** [comment]
As an update:

This does not appear to be an issue on my Windows 10 machine.

On Fri, Jun 24, 2016 at 10:43 AM, Chad Henson chad.henson@gmail.com wrote:

> On my Mac, i get a blue message box popup that usually says atom-force is
> attempting to save a file.  In the event the compilation fails, there will
> be a red box with the message that returns from the server saying something
> like "Expected a ; and found a <"  or some similar compile time anomaly.
> If I then fix the file to remedy the anomaly and attempt to save, I get no
> message box popup.  I don't even get the message box when I attempt to
> activate the org/nature.  Nor, do I get that message if I attempt to add
> the nature.  I don't even get the popup to "allow access...".  I have to go
> kill the metadatacontainer and then activate before I can save.
> 
> I will attempt this on my Windows 10 box to see if I get a similar
> scenario.
> 
> On Fri, Jun 24, 2016 at 10:37 AM, Mike Gedelman notifications@github.com
> wrote:
> 
> > I can't reproduce that last issue. You're saying if you save and the file
> > doesn't compile, then all subsequent saves don't try to save to the server?
> > Does restarting Atom solve it, or do you always have to delete and re-add
> > nature?
> > 
> > What's your console output look like after you save and the compile fails?
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > https://github.com/mikegedelman/atom-force/issues/2#issuecomment-228379211,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/AA7e2xRKMfhvktUjWBEfCo3RxmyzPyi2ks5qO_m5gaJpZM4I8VXi
> > .
> 
> ## 
> 
> To know is to have knowledge.....to understand is to be enlightened.

## 

To know is to have knowledge.....to understand is to be enlightened.

**Comment by mikegedelman** [comment]
I don't currently have access to a Mac, but I will in a week or so. But, if you can send me a dump of your console after saving with the error and then trying to save again, I might be able to spot the error there.

[Here's](http://stackoverflow.com/questions/7627113/save-the-console-log-in-chrome-to-a-file) an easy way to do that, you just right click anywhere in the console output and do Save As...

**Comment by cipherstream** [comment]
From my Mac.

Wonder if other plugins could be causing grief.

On Fri, Jun 24, 2016 at 11:11 AM, Mike Gedelman notifications@github.com
wrote:

> I don't currently have access to a Mac, but I will in a week or so. But,
> if you can send me a dump of your console after saving with the error and
> then trying to save again, I might be able to spot the error there.
> 
> Here's
> http://stackoverflow.com/questions/7627113/save-the-console-log-in-chrome-to-a-file
> an easy way to do that, you just right click anywhere in the console output
> and do Save As...
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/mikegedelman/atom-force/issues/2#issuecomment-228388900,
> or mute the thread
> https://github.com/notifications/unsubscribe/AA7e27UuEYQWskgbXlmZZ4FU2v03kuxQks5qPAHBgaJpZM4I8VXi
> .

## 

To know is to have knowledge.....to understand is to be enlightened.

**Comment by cipherstream** [comment]
Here is a log of an event that causes the failure of the atom-force plugin
to perform any further.  The prior one were of failures of the plugin "in
general", even when it successfully compiled the class.

On Fri, Jun 24, 2016 at 11:36 AM, Chad Henson chad.henson@gmail.com wrote:

> From my Mac.
> 
> Wonder if other plugins could be causing grief.
> 
> On Fri, Jun 24, 2016 at 11:11 AM, Mike Gedelman notifications@github.com
> wrote:
> 
> > I don't currently have access to a Mac, but I will in a week or so. But,
> > if you can send me a dump of your console after saving with the error and
> > then trying to save again, I might be able to spot the error there.
> > 
> > Here's
> > http://stackoverflow.com/questions/7627113/save-the-console-log-in-chrome-to-a-file
> > an easy way to do that, you just right click anywhere in the console output
> > and do Save As...
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > https://github.com/mikegedelman/atom-force/issues/2#issuecomment-228388900,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/AA7e27UuEYQWskgbXlmZZ4FU2v03kuxQks5qPAHBgaJpZM4I8VXi
> > .
> 
> ## 
> 
> To know is to have knowledge.....to understand is to be enlightened.

## 

To know is to have knowledge.....to understand is to be enlightened.

**Comment by mikegedelman** [comment]
Are you attaching files somewhere? I can't see them, but I might not know where to look.

**Comment by cipherstream** [comment]
I was attaching them to the email that was generated by GitHub, based upon your responses to the issue.  I bet they are being stripped, so I'm going to ship the log file that is most relevant to you through the GitHub browser interface.
[setMessages_fail.txt](https://github.com/mikegedelman/atom-force/files/332317/setMessages_fail.txt)
[setMessages_fail.txt](https://github.com/mikegedelman/atom-force/files/332318/setMessages_fail.txt)

**Comment by cipherstream** [comment]
whoops...attached twice...sorry

**Comment by mikegedelman** [comment]
Ah! Do you have the linter package installed on your Mac? I'm pretty sure that would cause this. The code's not failing gracefully when it can't find linter, it seems.

**Comment by cipherstream** [comment]
Haha...i don't.  I bet that is the issue.  I'm installing it now to verify.

**Comment by mikegedelman** [comment]
FYI, the original issue posted here, error message including `name duplicates value on id`, has been fixed in v0.3.4 and shouldn't be an issue anymore.
