### ISSUE TITLE
Small changes required for an upcoming Atom release

### ISSUE THREAD

**Issue by maxbrunsfeld** [mikegedelman/atom-force#3]
Hi! Atom will soon be upgrading to a new version of Electron, which will cause some APIs to change.

You'll need to change [this usage](https://github.com/mikegedelman/atom-force/blob/b05a6db6795f08edc2f18936ebecf9724b62e786/lib/atom-force.js#L163) of `BrowserWindow.prototype.loadUrl` to `win.webContents.loadURL`.

There may be other similar small changes required. See [this post](http://electron.atom.io/blog/2015/11/17/electron-api-changes) on the electron blog for more information. And let me know if you need any additional help. Thanks!

**Comment by mikegedelman** [comment]
Whoa! Thanks a bunch for finding me and telling me!

**Comment by maxbrunsfeld** [comment]
Ah, I forgot. You also should replace `import remote from 'remote'` with `import {remote} from 'electron'`

**Comment by mikegedelman** [comment]
Word, thanks again.
